import { IFormFactory } from "./contracts";

export const formFactory: IFormFactory[] = [
  {
    label: "Addresses (lat, long)",
    name: "addresses",
    fields: [
      {
        label: "Latitude",
        name: "latitude",
        type: "text",
        required: true,
        validate:
          "^-?([1-8]?[0-9](.d{1,4})?|90(.0{1,4})?)s*,s*-?((1[0-7]|[1-9])?d(.d{1,4})?|180(.0{1,4})?)$",
        validationMessage: "You should follow the format (+/-)##.#####",
      },
      {
        label: "Longitude",
        name: "longitude",
        type: "text",
        required: true,
        validate:
          "^-?([1-8]?[0-9](.d{1,4})?|90(.0{1,4})?)s*,s*-?((1[0-7]|[1-9])?d(.d{1,4})?|180(.0{1,4})?)$",
        validationMessage: "You should follow the format (+/-)###.#####",
      },
    ],
  },
  {
    label: "Distance Classes",
    name: "distanceClasses",
    type: "select",
    options: [
      { label: "onnetlabel", value: "onnetlabel" },
      { label: "nearnetlabel", value: "nearnetlabel" },
      { label: "offnetlabel", value: "offnetlabel" },
    ],
    required: true,
    validate: "^.*S+.*$",
    validationMessage: "You should select at least one distance class",
  },
  {
    label: "Technology Types",
    name: "technologyTypes",
    type: "select",
    options: [
      { label: "ADSL", value: "ADSL" },
      { label: "BSOD", value: "BSOD" },
      { label: "BVDSL", value: "BVDSL" },
      { label: "COAX", value: "COAX" },
      { label: "COPPER", value: "COPPER" },
      { label: "DSL", value: "DSL" },
      { label: "FIBER", value: "FIBER" },
      { label: "FOURG", value: "FOURG" },
      { label: "FTTB", value: "FTTB" },
      { label: "FTTC", value: "FTTC" },
      { label: "FTTE", value: "FTTE" },
      { label: "FTTH", value: "FTTH" },
      { label: "FTTN", value: "FTTN" },
      { label: "GPON", value: "GPON" },
      { label: "HFC", value: "HFC" },
      { label: "RADIO", value: "RADIO" },
      { label: "SATELLITE", value: "SATELLITE" },
      { label: "SDSL", value: "SDSL" },
      { label: "SHDSL", value: "SHDSL" },
      { label: "VDSL", value: "VDSL" },
    ],
    required: true,
    validate: "^.*S+.*$",
    validationMessage: "You should select one technology type",
  },
  {
    label: "Connection Types",
    name: "connectionTypes",
    type: "select",
    options: [
      { label: "DIA", value: "DIA" },
      { label: "ETHERNET_SHARED", value: "ETHERNET_SHARED" },
      { label: "ETHERNET_DEDICATED", value: "ETHERNET_DEDICATED" },
      { label: "SHARED", value: "SHARED" },
    ],
    required: true,
    validate: "^.*S+.*$",
    validationMessage: "You should select at least one connection type",
  },
  {
    label: "Networks Available",
    name: "networks",
    type: "select",
    options: [
      { label: "Renater", value: "Renater" },
      { label: "SONATEL", value: "SONATEL" },
      { label: "Vodaphone", value: "Vodaphone" },
      { label: "Latwan", value: "Latwan" },
    ],
    required: true,
    validate: "^.*S+.*$",
    validationMessage: "You should select at least one network",
  },
  {
    label: "Bandwidths (Mb)",
    name: "bandWidth",
    fields: [
      {
        label: "Download",
        name: "download",
        type: "text",
        required: true,
        validate: "^[0-9]+$",
        validationMessage: "You add at least one upload/download value",
      },
      {
        label: "Upload",
        name: "upload",
        type: "text",
        required: true,
        validate: "^[0-9]+$",
        validationMessage: "You add at least one upload/download value",
      },
    ],
  },
  {
    label: "Contract Terms",
    name: "contractTerms",
    type: "select",
    options: [
      { label: 12, value: 12 },
      { label: 24, value: 24 },
      { label: 36, value: 36 },
    ],
    required: true,
    validate: "^.*S+.*$",
    validationMessage: "You should select at least one contract option",
  },
  {
    label: "Area Codes",
    name: "areaCodes",
    type: "select",
    options: [
      { label: "Metro", value: "Metro" },
      { label: "Regio", value: "Regio" },
      { label: "Backbone", value: "Backbone" },
    ],
    required: false,
  },
];
